# This file was generated by GoReleaser. DO NOT EDIT.
cask "aft-ops" do
  version "0.16.0"

  on_macos do
    on_arm do
      sha256 "3ecd8a63c9b43312e2273295cdc00f119496a6369dccd79c04b51f8ba4fcc6d3"
      url "https://github.com/hacker65536/aft-ops/releases/download/v#{version}/aft-ops_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f8ee15aba1cee1bf88574e7e6f9d67b96c2315f476858922d4e295a0fc2851d9"
      url "https://github.com/hacker65536/aft-ops/releases/download/v#{version}/aft-ops_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "211e43ca2275b758c2cc8af1bbcd645557c5e3f0ddcc82fc269155f7df793dcc"
      url "https://github.com/hacker65536/aft-ops/releases/download/v#{version}/aft-ops_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f02d8a097dee35d9a1c38fca966e356e7e50788f71e6f905c10c25e3e6927f9c"
      url "https://github.com/hacker65536/aft-ops/releases/download/v#{version}/aft-ops_#{version}_linux_amd64.tar.gz"
    end
  end

  name "aft-ops"
  desc "Operate AWS Control Tower AFT customizations pipelines at scale"
  homepage "https://github.com/hacker65536/aft-ops"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aft-ops"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aft-ops"]
    end
  end

  # No zap stanza required
end
