# This file was generated by GoReleaser. DO NOT EDIT.
cask "aft-ops" do
  version "0.13.0"

  on_macos do
    on_intel do
      sha256 "9456dacea34e40fbd576f82377195f5d118485074a763dbafe513cab4775b64d"
      url "https://github.com/hacker65536/aft-ops/releases/download/v#{version}/aft-ops_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "86a654718a5459c956211e7b587249d0c7612111eda832c048f247cfd380fbe6"
      url "https://github.com/hacker65536/aft-ops/releases/download/v#{version}/aft-ops_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "461e7ffb380c616aecae3af6c681155b45daab58e5bf4bf70c74f821bac99388"
      url "https://github.com/hacker65536/aft-ops/releases/download/v#{version}/aft-ops_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4e985a9b1a4717b2e71054e70dd20d7f0883f0348929a00dbf9c501a9590d7bf"
      url "https://github.com/hacker65536/aft-ops/releases/download/v#{version}/aft-ops_#{version}_linux_arm64.tar.gz"
    end
  end

  name "aft-ops"
  desc "Operate AWS Control Tower AFT customizations pipelines at scale"
  homepage "https://github.com/hacker65536/aft-ops"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aft-ops"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aft-ops"]
    end
  end

  # No zap stanza required

end
