# This file was generated by GoReleaser. DO NOT EDIT.
cask "aft-ops" do
  version "0.15.0"

  on_macos do
    on_arm do
      sha256 "bc72bfc4bfa02bcf1d106b3325f84276d7baeaf64f5f7084972356fd1525511c"
      url "https://github.com/hacker65536/aft-ops/releases/download/v#{version}/aft-ops_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c2ea2ea19fd74029bd8ff08962d2fbaad5bf2350c1cb9955aec21ea4c5fbabeb"
      url "https://github.com/hacker65536/aft-ops/releases/download/v#{version}/aft-ops_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f8196016fc29a470c0b5713a0c7c4dc06c091aeba65ae3d167fbe6e3cec87f8a"
      url "https://github.com/hacker65536/aft-ops/releases/download/v#{version}/aft-ops_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7ffcb410e85dd5647ab2d0249c3805bad98c6110b746895fdac998b5f17ac9ce"
      url "https://github.com/hacker65536/aft-ops/releases/download/v#{version}/aft-ops_#{version}_linux_amd64.tar.gz"
    end
  end

  name "aft-ops"
  desc "Operate AWS Control Tower AFT customizations pipelines at scale"
  homepage "https://github.com/hacker65536/aft-ops"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aft-ops"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aft-ops"]
    end
  end

  # No zap stanza required
end
