# This file was generated by GoReleaser. DO NOT EDIT.
cask "aws-sso-profiles" do
  version "2.0.0"

  on_macos do
    on_intel do
      sha256 "8feda98cb7934cbea91ca2a52a023ff15026f7302be46bb95c8fb20780e2f2d4"
      url "https://github.com/hacker65536/aws-sso-profile-generator/releases/download/v#{version}/aws-sso-profiles_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6b7265dded6168042c824f3a9ebe96377eebe577dfca711c1124314758618e97"
      url "https://github.com/hacker65536/aws-sso-profile-generator/releases/download/v#{version}/aws-sso-profiles_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "171cd2cb802f2862c92d47d2b9c376e640a177830a12a8087f0b5c4809569eec"
      url "https://github.com/hacker65536/aws-sso-profile-generator/releases/download/v#{version}/aws-sso-profiles_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b1bdc77893c0f566e2d666145ee48ca63ab068b2bb7c487a25fabe704151f2d8"
      url "https://github.com/hacker65536/aws-sso-profile-generator/releases/download/v#{version}/aws-sso-profiles_linux_arm64.tar.gz"
    end
  end

  name "aws-sso-profiles"
  desc "Desired-state generator for AWS SSO profiles"
  homepage "https://github.com/hacker65536/aws-sso-profile-generator"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aws-sso-profiles"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aws-sso-profiles"]
    end
  end

  # No zap stanza required

end
