# This file was generated by GoReleaser. DO NOT EDIT.
cask "aws-sso-profiles" do
  version "2.2.0"

  on_macos do
    on_intel do
      sha256 "1cb09e120b162d74186384c5d4334e621100144f349245500c8b890144ebe680"
      url "https://github.com/hacker65536/aws-sso-profiles/releases/download/v#{version}/aws-sso-profiles_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4919938bacb95fe4b530971e847dbc866247fb8a669922e7f8ba43b1eeab0985"
      url "https://github.com/hacker65536/aws-sso-profiles/releases/download/v#{version}/aws-sso-profiles_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b3d28a6131c56a43100ae68f0772098086b3bb6762f7ce436a2df9af385e2c86"
      url "https://github.com/hacker65536/aws-sso-profiles/releases/download/v#{version}/aws-sso-profiles_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b728cbdfad5d608c04cb85c472604405247460dad3c4671559d18fe5ac867f8f"
      url "https://github.com/hacker65536/aws-sso-profiles/releases/download/v#{version}/aws-sso-profiles_linux_arm64.tar.gz"
    end
  end

  name "aws-sso-profiles"
  desc "Desired-state generator for AWS SSO profiles"
  homepage "https://github.com/hacker65536/aws-sso-profiles"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aws-sso-profiles"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aws-sso-profiles"]
    end
  end

  # No zap stanza required

end
