# This file was generated by GoReleaser. DO NOT EDIT.
cask "aws-sso-profiles" do
  version "2.1.0"

  on_macos do
    on_intel do
      sha256 "caa78acbede6829ab9cba9ed215abc912b1a21229d9a94e484cb28c6d7ce90ac"
      url "https://github.com/hacker65536/aws-sso-profiles/releases/download/v#{version}/aws-sso-profiles_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "09f39a1662c380858e21c7e8bea28efb92c1a1d4a87ea92d0131e3625c86cf32"
      url "https://github.com/hacker65536/aws-sso-profiles/releases/download/v#{version}/aws-sso-profiles_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "84ef2ed0d0877aef0dcc8dd4133f8bc1ec6449f973aa004b128486605b22fd34"
      url "https://github.com/hacker65536/aws-sso-profiles/releases/download/v#{version}/aws-sso-profiles_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "94df39010f8f0c536bfc60ef78a40f8eae6c98a33037e4e29a65c4f253e2d5db"
      url "https://github.com/hacker65536/aws-sso-profiles/releases/download/v#{version}/aws-sso-profiles_linux_arm64.tar.gz"
    end
  end

  name "aws-sso-profiles"
  desc "Desired-state generator for AWS SSO profiles"
  homepage "https://github.com/hacker65536/aws-sso-profiles"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aws-sso-profiles"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aws-sso-profiles"]
    end
  end

  # No zap stanza required

end
