# This file was generated by GoReleaser. DO NOT EDIT.
cask "phd" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "6259e6f0f4b11a36a4d4c705db5c492df2335e00ae04e056d573eee02784fa9c"
      url "https://github.com/hacker65536/phd/releases/download/v#{version}/phd_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3fa724531a1ec9578ddf8a07ac561fa6914df1bb717e8527ecfde9c3c11195d5"
      url "https://github.com/hacker65536/phd/releases/download/v#{version}/phd_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7614d0be065b10d37df5a4d7edbc9a63070f567af5859ede285c7fb2d200bca2"
      url "https://github.com/hacker65536/phd/releases/download/v#{version}/phd_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c216025edd842d028d367c9cb4b8647d90ec839e53e5ff0e16a2bd154ec0748f"
      url "https://github.com/hacker65536/phd/releases/download/v#{version}/phd_#{version}_linux_arm64.tar.gz"
    end
  end

  name "phd"
  desc "AWS Health Dashboard をローカルで確認する CLI / TUI"
  homepage "https://github.com/hacker65536/phd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "phd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/phd"]
    end
  end

  # No zap stanza required

end
