# This file was generated by GoReleaser. DO NOT EDIT.
cask "phd" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "9c9184edc5bf6b09bccc4c36306dc45a18117eb029509d4f913bda343beaed4d"
      url "https://github.com/hacker65536/phd/releases/download/v#{version}/phd_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "71396ca045a3b1a19f2cf20d7179ff279cfbe8b32843bd91cf1002999e0394a4"
      url "https://github.com/hacker65536/phd/releases/download/v#{version}/phd_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d204714140af7d7432380c50567d152b4131ea7045b1444b2984b4b222798c11"
      url "https://github.com/hacker65536/phd/releases/download/v#{version}/phd_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5aba8b164acd1443abdd99fd70d22fe94809361b45940ec7c20f15dcff012326"
      url "https://github.com/hacker65536/phd/releases/download/v#{version}/phd_#{version}_linux_arm64.tar.gz"
    end
  end

  name "phd"
  desc "AWS Health Dashboard をローカルで確認する CLI / TUI"
  homepage "https://github.com/hacker65536/phd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "phd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/phd"]
    end
  end

  # No zap stanza required

end
