# This file was generated by GoReleaser. DO NOT EDIT.
cask "phd" do
  version "0.5.1"

  on_macos do
    on_intel do
      sha256 "e149825e0428d71cab48e9277688b99bf492c29819d482269fba492cf12a62fc"
      url "https://github.com/hacker65536/phd/releases/download/v#{version}/phd_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1484fac96ae81853818b790e9d82260129a145cd7b284f5a122d855362c93571"
      url "https://github.com/hacker65536/phd/releases/download/v#{version}/phd_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "76066fb41e2ce7f8ee1333bdbc2aa787b0c67e17284d2f36c40fc3043946b3b6"
      url "https://github.com/hacker65536/phd/releases/download/v#{version}/phd_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5a0578b21230312ec97819c821873cc8e18cde40052f28f1b905fd84b99835e0"
      url "https://github.com/hacker65536/phd/releases/download/v#{version}/phd_#{version}_linux_arm64.tar.gz"
    end
  end

  name "phd"
  desc "AWS Health Dashboard をローカルで確認する CLI / TUI"
  homepage "https://github.com/hacker65536/phd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "phd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/phd"]
    end
  end

  # No zap stanza required

end
